export const ROUTE_ROOT_TABS: string = 'RootTabs';

export const ROUTE_BUS: string = 'Bus';
export const ROUTE_CAR_PARK: string = 'CarPark';
export const ROUTE_UM_ORG: string = 'UMOrg';
export const ROUTE_COURSE_SIM: string = 'CourseSimTab';
export const ROUTE_SETTING: string = 'SettingPage';

export const ROUTE_CLUB_DETAIL: string = 'ClubDetail';
export const ROUTE_EVENT_DETAIL: string = 'EventDetail';
export const ROUTE_NEWS_DETAIL: string = 'NewsDetail';
export const ROUTE_UM_EVENT_DETAIL: string = 'UMEventDetail';
export const ROUTE_ALL_EVENTS: string = 'AllEvents';
export const ROUTE_LOCAL_COURSE: string = 'LocalCourse';
export const ROUTE_WEBVIEWER: string = 'Webviewer';
