export const APP_PREFERENCES_NAME: string = 'umarkall_preferences';

export const STORAGE_THEME_PREFERENCE: string = 'themePreference';
export const STORAGE_LANGUAGE: string = 'language';
export const STORAGE_COURSE_VERSION: string = 'course_version';
export const STORAGE_OFFER_COURSES: string = 'offer_courses';
export const STORAGE_COURSE_PLAN: string = 'course_plan';
export const STORAGE_COURSE_PLAN_TIME: string = 'course_plan_time';
export const STORAGE_COURSE_FILTER_OPTIONS: string = 'ARK_Courses_filterOptions';
export const STORAGE_TIMETABLE: string = 'ARK_Timetable_Storage';
export const STORAGE_WEEK_TIMETABLE: string = 'ARK_WeekTimetable_Storage';
export const STORAGE_NEXT_CLASS_FORM_IDS: string = 'ARK_NextClass_FormIds';
export const STORAGE_LAST_VERSION_CHECK_TIMESTAMP: string = 'last_version_check_timestamp';
export const STORAGE_USER_INFO: string = 'userInfo';
export const STORAGE_APP_INFO: string = 'appInfo';
export const STORAGE_UM_PASS: string = 'umPass';
export const STORAGE_HARBOR_SETTING: string = 'ARK_Harbor_Setting';
export const STORAGE_UMEH_HOST_PREF: string = 'umeh_host_pref';

export const BUSINESS_STORAGE_KEYS: string[] = [
  STORAGE_THEME_PREFERENCE,
  STORAGE_LANGUAGE,
  STORAGE_COURSE_VERSION,
  STORAGE_OFFER_COURSES,
  STORAGE_COURSE_PLAN,
  STORAGE_COURSE_PLAN_TIME,
  STORAGE_COURSE_FILTER_OPTIONS,
  STORAGE_TIMETABLE,
  STORAGE_WEEK_TIMETABLE,
  STORAGE_NEXT_CLASS_FORM_IDS,
  STORAGE_LAST_VERSION_CHECK_TIMESTAMP,
  STORAGE_USER_INFO,
  STORAGE_APP_INFO,
  STORAGE_UM_PASS,
  STORAGE_HARBOR_SETTING,
  STORAGE_UMEH_HOST_PREF
];

export const CACHE_RESET_STORAGE_KEYS: string[] = [
  STORAGE_COURSE_VERSION,
  STORAGE_OFFER_COURSES,
  STORAGE_COURSE_PLAN,
  STORAGE_COURSE_PLAN_TIME,
  STORAGE_COURSE_FILTER_OPTIONS,
  STORAGE_TIMETABLE,
  STORAGE_WEEK_TIMETABLE,
  STORAGE_LAST_VERSION_CHECK_TIMESTAMP,
  STORAGE_USER_INFO,
  STORAGE_APP_INFO,
  STORAGE_HARBOR_SETTING,
  STORAGE_UMEH_HOST_PREF
];
